# Generated by Django 6.0.4 on 2026-04-13 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('ordering_physician', models.CharField(max_length=200)),
                ('ordering_facility', models.CharField(max_length=200)),
                ('patient_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('STAT', 'STAT'), ('RESEARCH', 'Research')], default='ROUTINE', max_length=10)),
                ('clinical_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SAMPLED', 'Sampled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
