# Generated by Django 6.0.4 on 2026-04-27 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('samples', '0004_sample_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='samples.sample'),
        ),
    ]
