# Generated by Django 6.0.4 on 2026-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=20)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_email', models.CharField(max_length=254)),
                ('user_role', models.CharField(blank=True, max_length=100)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('entity_repr', models.CharField(blank=True, max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('site_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('request_id', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=128)),
                ('row_hash', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['user_id'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx')],
            },
        ),
    ]
