# Generated by Django 6.0.4 on 2026-05-12 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('samples', '0005_rename_barcode_sample_sample_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('FREEZER', 'Freezer (-80°C/-20°C)'), ('REFRIGERATOR', 'Refrigerator (4°C)'), ('ROOM_TEMP', 'Room Temperature'), ('LN2', 'Liquid Nitrogen')], max_length=30)),
                ('barcode', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent location (e.g., Freezer contains Shelves)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='storage.storagelocation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_locations', to='organizations.site')),
            ],
            options={
                'db_table': 'storage_locations',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(blank=True, max_length=100, unique=True)),
                ('box_size', models.CharField(choices=[('9x9', '9×9 (81)'), ('10x10', '10×10 (100)')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='organizations.site')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='storage.storagelocation')),
            ],
            options={
                'verbose_name_plural': 'boxes',
                'db_table': 'storage_boxes',
            },
        ),
        migrations.CreateModel(
            name='BoxPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row', models.CharField(max_length=3)),
                ('col', models.PositiveSmallIntegerField()),
                ('occupied_at', models.DateTimeField(blank=True, null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='storage.box')),
                ('sample', models.ForeignKey(blank=True, help_text='Sample occupying this position (null = empty)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_positions', to='samples.sample')),
            ],
            options={
                'db_table': 'storage_box_positions',
                'ordering': ['box', 'row', 'col'],
                'unique_together': {('box', 'row', 'col')},
            },
        ),
    ]
