# Generated by Django 6.0.4 on 2026-04-13 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('organizations', '0001_initial'),
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('steps_definition', models.JSONField(help_text='JSON array of step definitions')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='samples.testpanel')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_protocols',
                'unique_together': {('panel', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SampleRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_number', models.CharField(db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('LIBRARY_PREP', 'Library Prep'), ('SEQUENCING', 'Sequencing'), ('ANALYZING', 'Analyzing'), ('QC_REVIEW', 'QC Review'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PLANNED', max_length=20)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='samples.testpanel')),
                ('sequencer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='organizations.site')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflows.workflowprotocol')),
            ],
            options={
                'db_table': 'sample_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_id', models.CharField(max_length=50)),
                ('step_name', models.CharField(max_length=100)),
                ('step_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reagents_used', models.JSONField(blank=True, default=list)),
                ('observations', models.TextField(blank=True)),
                ('deviation_flag', models.BooleanField(default=False)),
                ('deviation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instruments.instrument')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.samplerun')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='samples.sample')),
            ],
            options={
                'db_table': 'workflow_steps',
                'ordering': ['run', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='RunSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('well_position', models.CharField(blank=True, max_length=5)),
                ('plate_number', models.PositiveIntegerField(default=1)),
                ('index_sequence', models.CharField(blank=True, max_length=50)),
                ('index_combo_id', models.CharField(blank=True, max_length=20)),
                ('pool_group', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('SEQUENCED', 'Sequenced'), ('ANALYZED', 'Analyzed'), ('PASSED_QC', 'Passed QC'), ('FAILED_QC', 'Failed QC')], db_index=True, default='QUEUED', max_length=20)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_samples', to='samples.sample')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_samples', to='workflows.samplerun')),
            ],
            options={
                'db_table': 'run_samples',
                'unique_together': {('run', 'sample')},
            },
        ),
    ]
