# Generated by Django 6.0.4 on 2026-04-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsample',
            name='barcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='samplerun',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
