# Generated by Django 6.0.4 on 2026-04-13 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_title', models.CharField(max_length=200)),
                ('audit_date', models.DateField()),
                ('scope', models.TextField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'internal_audits',
            },
        ),
        migrations.CreateModel(
            name='PTProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('program_code', models.CharField(max_length=50, unique=True)),
                ('frequency', models.CharField(choices=[('QUARTERLY', 'Quarterly'), ('SEMI_ANNUALLY', 'Semi-Annually'), ('ANNUALLY', 'Annually')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pt_programs',
            },
        ),
        migrations.CreateModel(
            name='PTRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.CharField(max_length=20)),
                ('sample_received_date', models.DateField()),
                ('submission_deadline', models.DateField()),
                ('submission_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('SCORED', 'Scored'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('SATISFACTORY', 'Satisfactory'), ('UNSATISFACTORY', 'Unsatisfactory'), ('MARGINAL', 'Marginal')], max_length=20, null=True)),
                ('score', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pt_rounds',
            },
        ),
    ]
