# Generated by Django 6.0.4 on 2026-04-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('quality', '0001_initial'),
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalaudit',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_audits', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='ptprogram',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pt_programs', to='samples.testpanel'),
        ),
        migrations.AddField(
            model_name='ptprogram',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pt_programs', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='ptround',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='quality.ptprogram'),
        ),
        migrations.AddField(
            model_name='ptround',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pt_rounds', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='ptround',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
