# Generated by Django 6.0.4 on 2026-04-30 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=100, verbose_name='名称(中)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='名称(英)')),
                ('name_pt', models.CharField(blank=True, max_length=100, verbose_name='名称(葡)')),
                ('level', models.CharField(choices=[('federal', '联邦'), ('state', '州级'), ('municipal', '市级')], default='federal', max_length=20, verbose_name='层级')),
                ('description_cn', models.TextField(blank=True, verbose_name='描述(中)')),
            ],
            options={
                'verbose_name': '管辖层级',
                'verbose_name_plural': '管辖层级',
                'ordering': ['level', 'name_cn'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=100, verbose_name='分类名称(中)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='分类名称(英)')),
                ('name_pt', models.CharField(blank=True, max_length=100, verbose_name='分类名称(葡)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类代码')),
                ('description_cn', models.TextField(blank=True, verbose_name='描述(中)')),
                ('description_en', models.TextField(blank=True, verbose_name='描述(英)')),
                ('description_pt', models.TextField(blank=True, verbose_name='描述(葡)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='regulatory.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '法规分类',
                'verbose_name_plural': '法规分类',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_number', models.CharField(db_index=True, max_length=100, verbose_name='法规编号')),
                ('title_cn', models.CharField(max_length=300, verbose_name='标题(中)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='标题(英)')),
                ('title_pt', models.CharField(max_length=300, verbose_name='标题(葡-原文)')),
                ('doc_type', models.CharField(choices=[('law', '法律(Lei)'), ('decree', '法令(Decreto)'), ('mp', '临时措施(Medida Provisória)'), ('rdc', 'ANVISA决议(RDC)'), ('ordinance', '部令(Portaria)'), ('ni', '规范指令(IN)'), ('resolution', '决议(Resolução)'), ('constitution', '宪法'), ('treaty', '国际条约')], default='law', max_length=30, verbose_name='文件类型')),
                ('issuing_authority_cn', models.CharField(max_length=200, verbose_name='发布机构(中)')),
                ('issuing_authority_en', models.CharField(blank=True, max_length=200, verbose_name='发布机构(英)')),
                ('issuing_authority_pt', models.CharField(blank=True, max_length=200, verbose_name='发布机构(葡)')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('revoked_date', models.DateField(blank=True, null=True, verbose_name='废止日期')),
                ('status', models.CharField(choices=[('active', '有效'), ('amended', '已修订'), ('revoked', '已废止'), ('pending', '待定/草案')], default='active', max_length=20, verbose_name='状态')),
                ('summary_cn', models.TextField(blank=True, verbose_name='摘要(中)')),
                ('summary_en', models.TextField(blank=True, verbose_name='摘要(英)')),
                ('summary_pt', models.TextField(blank=True, verbose_name='摘要(葡)')),
                ('full_text_cn', models.TextField(blank=True, verbose_name='全文(中)')),
                ('full_text_en', models.TextField(blank=True, verbose_name='全文(英)')),
                ('full_text_pt', models.TextField(blank=True, verbose_name='全文(葡-原文)')),
                ('official_link', models.URLField(blank=True, verbose_name='官方链接')),
                ('pdf_url', models.URLField(blank=True, verbose_name='PDF链接')),
                ('keywords_cn', models.CharField(blank=True, help_text='逗号分隔', max_length=500, verbose_name='关键词(中)')),
                ('keywords_en', models.CharField(blank=True, max_length=500, verbose_name='关键词(英)')),
                ('keywords_pt', models.CharField(blank=True, max_length=500, verbose_name='关键词(葡)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('amends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amended_by', to='regulatory.regulation', verbose_name='修订/替代')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regulations', to='regulatory.category', verbose_name='所属分类')),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulations', to='regulatory.jurisdiction', verbose_name='管辖层级')),
                ('related_regulations', models.ManyToManyField(blank=True, to='regulatory.regulation', verbose_name='关联法规')),
            ],
            options={
                'verbose_name': '法规',
                'verbose_name_plural': '法规',
                'ordering': ['-effective_date', 'regulation_number'],
            },
        ),
        migrations.CreateModel(
            name='RegulationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(blank=True, max_length=50, verbose_name='条款编号')),
                ('title_cn', models.CharField(blank=True, max_length=300, verbose_name='条款标题(中)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='条款标题(英)')),
                ('title_pt', models.CharField(blank=True, max_length=300, verbose_name='条款标题(葡)')),
                ('content_cn', models.TextField(blank=True, verbose_name='条款内容(中)')),
                ('content_en', models.TextField(blank=True, verbose_name='条款内容(英)')),
                ('content_pt', models.TextField(blank=True, verbose_name='条款内容(葡-原文)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('tags_cn', models.CharField(blank=True, max_length=300, verbose_name='标签(中)')),
                ('parent_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_articles', to='regulatory.regulationarticle', verbose_name='父条款')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='regulatory.regulation', verbose_name='所属法规')),
            ],
            options={
                'verbose_name': '法规条款',
                'verbose_name_plural': '法规条款',
                'ordering': ['regulation', 'sort_order', 'article_number'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryQALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_cn', models.TextField(verbose_name='问题(中)')),
                ('question_en', models.TextField(blank=True, verbose_name='问题(英)')),
                ('question_pt', models.TextField(blank=True, verbose_name='问题(葡)')),
                ('answer_cn', models.TextField(verbose_name='回答(中)')),
                ('answer_en', models.TextField(blank=True, verbose_name='回答(英)')),
                ('answer_pt', models.TextField(blank=True, verbose_name='回答(葡)')),
                ('source', models.CharField(default='manual', max_length=50, verbose_name='回答来源')),
                ('confidence', models.CharField(blank=True, max_length=20, verbose_name='可信度')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='有用投票')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('referenced_articles', models.ManyToManyField(blank=True, to='regulatory.regulationarticle', verbose_name='引用条款')),
                ('referenced_regulations', models.ManyToManyField(blank=True, to='regulatory.regulation', verbose_name='引用法规')),
            ],
            options={
                'verbose_name': '法规问答记录',
                'verbose_name_plural': '法规问答记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='regulation',
            index=models.Index(fields=['category', 'status'], name='regulatory__categor_bc5980_idx'),
        ),
        migrations.AddIndex(
            model_name='regulation',
            index=models.Index(fields=['doc_type', 'status'], name='regulatory__doc_typ_e9d0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='regulation',
            index=models.Index(fields=['keywords_cn'], name='idx_kw_cn'),
        ),
    ]
