# Generated by Django 6.0.4 on 2026-04-13 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QCChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('target_mean', models.DecimalField(decimal_places=4, max_digits=10)),
                ('target_sd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('warning_sd', models.DecimalField(decimal_places=4, default=2, max_digits=10)),
                ('action_sd', models.DecimalField(decimal_places=4, default=3, max_digits=10)),
                ('westgard_rules', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qc_charts',
            },
        ),
        migrations.CreateModel(
            name='QCControlMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NTC', 'No Template Control'), ('REFERENCE', 'Reference')], max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('catalog_number', models.CharField(blank=True, max_length=100)),
                ('lot_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('target_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qc_control_materials',
            },
        ),
        migrations.CreateModel(
            name='QCEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('QC_FAILURE', 'QC Failure'), ('PT_UNSATISFACTORY', 'PT Unsatisfactory'), ('DEVIATION', 'Deviation'), ('INSTRUMENT_FAILURE', 'Instrument Failure'), ('CUSTOMER_COMPLAINT', 'Customer Complaint')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('affected_samples', models.JSONField(blank=True, default=list)),
                ('affected_reports', models.JSONField(blank=True, default=list)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('preventive_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qc_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measured_values', models.JSONField(default=dict)),
                ('pass_fail', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('REVIEW', 'Review')], max_length=10)),
                ('westgard_violations', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qc_runs',
            },
        ),
    ]
