# Generated by Django 6.0.4 on 2026-04-13 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('qc', '0001_initial'),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcchart',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_charts', to='samples.testpanel'),
        ),
        migrations.AddField(
            model_name='qcchart',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_charts', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='qccontrolmaterial',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_materials', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='qcchart',
            name='control_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qc.qccontrolmaterial'),
        ),
    ]
