# Generated by Django 6.0.4 on 2026-04-13 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('additional_barcodes', models.JSONField(blank=True, default=list)),
                ('patient_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, max_length=1)),
                ('ordering_physician', models.CharField(blank=True, max_length=200)),
                ('ordering_facility', models.CharField(blank=True, max_length=200)),
                ('collection_date', models.DateField()),
                ('collection_time', models.TimeField(blank=True, null=True)),
                ('receipt_date', models.DateField()),
                ('receipt_time', models.TimeField()),
                ('receipt_temp', models.CharField(blank=True, max_length=10)),
                ('transport_time_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_PROCESS', 'In Process'), ('COMPLETED', 'Completed'), ('REPORTED', 'Reported'), ('ARCHIVED', 'Archived'), ('DISPOSED', 'Disposed')], db_index=True, default='RECEIVED', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=100)),
                ('rejection_note', models.TextField(blank=True)),
                ('consent_given', models.BooleanField(blank=True, null=True)),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleAliquot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aliquot_type', models.CharField(max_length=50)),
                ('volume_ml', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sample_aliquots',
            },
        ),
        migrations.CreateModel(
            name='SampleMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_location', models.CharField(blank=True, max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=100)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sample_movements',
                'ordering': ['performed_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('collection_tube', models.CharField(blank=True, max_length=200)),
                ('storage_temp', models.CharField(blank=True, max_length=20)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sample_types',
            },
        ),
        migrations.CreateModel(
            name='TestPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('turnaround_days', models.PositiveIntegerField(default=7)),
                ('report_template_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'test_panels',
            },
        ),
    ]
