# Generated by Django 6.0.4 on 2026-04-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        ('organizations', '0001_initial'),
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='samplealiquot',
            name='child_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_of', to='samples.sample'),
        ),
        migrations.AddField(
            model_name='samplealiquot',
            name='parent_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliquots', to='samples.sample'),
        ),
        migrations.AddField(
            model_name='samplemovement',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplemovement',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='samples.sample'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.sampletype'),
        ),
        migrations.AddField(
            model_name='testpanel',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_panels', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='testpanel',
            name='sop_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['site', 'is_deleted', 'status'], name='samples_site_id_6cb4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['site', 'receipt_date'], name='samples_site_id_127010_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['patient_id', 'site'], name='samples_patient_294405_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testpanel',
            unique_together={('code', 'site')},
        ),
    ]
