# Generated by Django 5.2.13 on 2026-04-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('samples', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='organizations.site'),
        ),
    ]
