# Generated by Django 6.0.4 on 2026-04-27 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_sample_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='samples.testpanel'),
        ),
    ]
