# Generated by Django 6.0.4 on 2026-04-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_sample_panel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='barcode',
            new_name='sample_id',
        ),
        migrations.RenameField(
            model_name='samplealiquot',
            old_name='barcode',
            new_name='sample_id',
        ),
    ]
