# Generated by Django 6.0.4 on 2026-04-13 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('DIRECT_OBSERVATION', 'Direct Observation of Routine Patient Test Performance'), ('MONITORING', 'Monitoring Recording and Reporting'), ('INTERMEDIATE_REVIEW', 'Review of Intermediate Test Results'), ('INSTRUMENT_MAINTENANCE', 'Direct Observation of Instrument Maintenance'), ('BLIND_SAMPLE', 'Blind Sample Testing'), ('PROBLEM_SOLVING', 'Problem Solving Skills')], max_length=50)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('NEEDS_IMPROVEMENT', 'Needs Improvement')], max_length=20)),
                ('assessment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'competency_assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('training_type', models.CharField(choices=[('SOP_REVIEW', 'SOP Review'), ('EXTERNAL', 'External Course'), ('INTERNAL', 'Internal Training'), ('ONBOARDING', 'Onboarding')], max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_records',
            },
        ),
    ]
