# Generated by Django 6.0.4 on 2026-04-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        ('organizations', '0001_initial'),
        ('samples', '0002_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyassessment',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='samples.testpanel'),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competency_assessments', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.document'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
