# Generated by Django 6.0.4 on 2026-04-13 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('RECEIVED', 'Received'), ('USED', 'Used'), ('RETURNED', 'Returned'), ('ADJUSTED', 'Adjusted'), ('EXPIRED', 'Expired'), ('DISCARDED', 'Discarded')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('catalog_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('reagent_type', models.CharField(choices=[('KIT', 'Kit'), ('ENZYME', 'Enzyme'), ('PRIMER', 'Primer'), ('CONTROL', 'Control'), ('CONSUMABLE', 'Consumable')], default='KIT', max_length=50)),
                ('storage_temp', models.CharField(blank=True, max_length=20)),
                ('hazardous', models.BooleanField(default=False)),
                ('cas_number', models.CharField(blank=True, max_length=20)),
                ('sds_file_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'reagents',
            },
        ),
        migrations.CreateModel(
            name='ReagentLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=100)),
                ('coa_file_path', models.CharField(blank=True, max_length=500)),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('storage_location', models.CharField(blank=True, max_length=200)),
                ('quality_status', models.CharField(choices=[('PENDING_QC', 'Pending QC'), ('QC_PASSED', 'QC Passed'), ('QC_FAILED', 'QC Failed'), ('IN_USE', 'In Use'), ('EXPIRED', 'Expired'), ('DEPLETED', 'Depleted')], default='PENDING_QC', max_length=20)),
                ('qc_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reagent_lots',
            },
        ),
    ]
