# Generated by Django 6.0.4 on 2026-04-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('reagents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reagent',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reagents', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='reagentlot',
            name='reagent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='reagents.reagent'),
        ),
        migrations.AddField(
            model_name='reagentlot',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='reagents.reagentlot'),
        ),
        migrations.AlterUniqueTogether(
            name='reagentlot',
            unique_together={('reagent', 'lot_number')},
        ),
    ]
