# Generated by Django 6.0.4 on 2026-04-13 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('input_files', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('output_files', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('callback_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'analysis_jobs',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(max_length=20)),
                ('engine', models.CharField(choices=[('NEXTFLOW', 'Nextflow'), ('SNAKEMAKE', 'Snakemake'), ('CWL', 'CWL')], max_length=20)),
                ('reference_genome', models.CharField(default='GRCh38', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('RETIRED', 'Retired')], default='IN_PROGRESS', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pipelines',
            },
        ),
        migrations.CreateModel(
            name='PipelineValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sensitivity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('specificity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reproducibility', models.TextField(blank=True)),
                ('samples_tested', models.PositiveIntegerField(default=0)),
                ('reference_method', models.CharField(blank=True, max_length=200)),
                ('validated_at', models.DateTimeField()),
                ('validation_report', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pipeline_validations',
            },
        ),
    ]
