# Generated by Django 6.0.4 on 2026-04-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bioinformatics', '0001_initial'),
        ('organizations', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='workflows.samplerun'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bioinformatics.pipeline'),
        ),
        migrations.AddField(
            model_name='pipelinevalidation',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='bioinformatics.pipeline'),
        ),
        migrations.AddField(
            model_name='pipelinevalidation',
            name='validated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('code', 'version')},
        ),
    ]
