# Generated by Django 6.0.4 on 2026-04-13 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_local', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cap_number', models.CharField(blank=True, max_length=20)),
                ('clia_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('data_residency', models.CharField(default='central', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sites',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.site')),
            ],
            options={
                'db_table': 'departments',
                'unique_together': {('site', 'code')},
            },
        ),
    ]
