# Generated by Django 6.0.4 on 2026-05-12 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodePrinter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('printer_type', models.CharField(choices=[('ZEBRA', 'Zebra'), ('BROTHER', 'Brother'), ('DYMO', 'Dymo'), ('GENERIC', 'Generic')], max_length=30)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('port', models.IntegerField(default=9100)),
                ('label_width_mm', models.IntegerField(default=50)),
                ('label_height_mm', models.IntegerField(default=25)),
                ('dpi', models.IntegerField(default=203)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcode_printers', to='organizations.site')),
            ],
            options={
                'db_table': 'barcode_printers',
            },
        ),
        migrations.CreateModel(
            name='BarcodeLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('label_type', models.CharField(choices=[('SAMPLE', 'Sample Tube'), ('BOX', 'Storage Box'), ('REAGENT', 'Reagent'), ('GENERIC', 'Generic')], max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('copies', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcode_labels', to='organizations.site')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barcodes.barcodeprinter')),
            ],
            options={
                'db_table': 'barcode_labels',
            },
        ),
    ]
